Code review
Genesis-Front-End-School/clean-code-principes-artemsukach pull request #2
Opened 2023-04-14 09:56 UTC by artemsukach

2023-04-14 15:29 UTC, v4voloshyn commented on src/pages/ErrorPage/ErrorPage.scss
> +    left: var(--mouse-x);
Повторення у коді top, left

2023-04-15 08:27 UTC, v4voloshyn commented on src/components/Video/Video.js
> +  };
Я б цю функцію виніс в окремий хелпер або в окреми хук usePlaybackRateChange, типу `const usePlaybackRateChange = (pressedKey, videoRef) => {}`

2023-04-15 08:51 UTC, artemsukach commented on src/components/Video/Video.js
> +  };
Не погоджусь з тобою. Вона досить специфічна і використовується лиш в загальному компоненті Video, який може використовуватись будь-деінде. 
«Создание пользовательских хуков позволяет вам перенести логику компонентов в функции, которые можно повторно использовать.» Це з документації React. 
Якби нам потрібно було ще десь опрацьовувати натискання клавіш, тоді можна було б змінити логіку, зробити її більш універсальною і винести в окремий хук. А так я поки не бачу місця де його ще можна використовувати і виносити в окремий хук це зайва дія.
Знову ж таки, це моя думка. Тут напевно Влад підкаже як краще)

2023-04-15 11:27 UTC, v4voloshyn commented on src/components/Video/Video.js
> +  });
З документації реакт стововно useBeforeUnload: `` export declare function useBeforeUnload(callback: (event: BeforeUnloadEvent) => any, options?: {
    capture?: boolean;
}): void ``

/** The `callback` argument should be a function created with
 * `React.useCallback()`.
 */

2023-04-15 11:49 UTC, v4voloshyn commented on src/components/Video/Video.js
> +  };
Тіло розгалудження if має бути відокремлене від умови фігурними скобками: ``const onEndedLoop = () => {
    if (isCardVideo && !showPreview) {
		 playVideo();
	 }
  }; ``

2023-04-15 11:51 UTC, v4voloshyn commented on src/components/Video/Video.js
> +        // onProgress={handleProgress}
Забув видалити комент :)

2023-04-15 12:02 UTC, v4voloshyn commented on src/components/Lesson/Lesson.js
> +          </h2>
Я б інструкцію про перемикачі швидкості а також назву відео закинув би в компонент відео, так як це безпосередьо відео компонента стосується. Ну і показував би цей опис і перемикачі через пропс, який ти вже маєш `isCardVideo = false`

2023-04-15 12:10 UTC, v4voloshyn commented on src/components/Video/Video.js
> +  };
Ти правий. З хуком я погарячкував :) Хоча цікаво теж почути думку [Влада](@vlad-khozhai)

2023-04-15 12:30 UTC, v4voloshyn commented on hooks/useUnload.js
Unused hook in the code

2023-04-15 19:32 UTC, v4voloshyn commented on src/pages/router.js
В ``` createBrowserRouter ``` потрібно, мабуть, виставити індексний компонент в чілдренах лейаута, інакше буде рендеритись пустий лейаут. Компонент ``CoursesList`` в тебе рендериться по шляху `{hostname}/courses`

Загалом я ще пробував білдити проект і запускати білд локально через ```serve ./dist```, але в мене рендериться пустий лейаут (стилі бачу підвантажились в bundle.js ), але роути не працюють ніякі. Хоча і в консолі помилки не видає і в нетворку теж нічого не видно. Дебажити глибше я не став та і не знаю чи на то варто звертати увагу взагалі, якщо чесно. Нехай @vlad-khozhai вирішує :)

2023-04-16 14:07 UTC, v4voloshyn commented on src/components/Pagination/Pagination.js
> +              &#8230;
Мабуть тут мало б бути: ```{ DOTS }```

2023-04-16 14:13 UTC, v4voloshyn commented on src/components/Pagination/Pagination.js
> +            }`}
Тут і взагалі по всьому коді: стилі які залежать від тих чи інших пропсів можливо ліпше виносити в константи, а не прописувати умову в JSX розмітці? Засмічення коду тернарниками трохи йде. Глянь на [classnames](https://www.npmjs.com/package/classnames) або на [clsx](https://www.npmjs.com/package/clsx) утиліти які допомагають в цьому.

2023-04-16 14:19 UTC, v4voloshyn commented on src/components/Pagination/Pagination.scss
> +    /* By using an em scale, the arrows will size with the font */
Чи обовязково потрібні ці коментарі в коді?

2023-04-16 14:25 UTC, v4voloshyn commented on src/components/Popup/Popup.scss
> +}
Тут лаконічно виглядатиме scss наслідування. Можна перемістити властивості і класи які належать чи наслідуються від popup'a в самий popup:
```
.popup {
  .close:hover {
    cursor: pointer;
    opacity: 0.9;
  }

  .content {
    max-height: 30%;
  }
}
...
```

2023-04-16 14:47 UTC, v4voloshyn commented on utils/constants.js
> +export const KEY_PLAYBACK_RATE = ['u', 'i'];
Можливо краще зробити цю константу обєктом з більш конретною назвою властивостей. Наприклад: 
```
export const KEY_PLAYBACK_RATE = {
	SPEED_UP: 'i',
	SLOW_DOWN: 'u'
}
```
І далі використовуючи цей обєкт звертатись до його властивостей. І раптом зміняться назначені keyCodes, наприклад на  '>' & '<', то правки тільки в цьому файлі потрібно робити.

2023-04-16 15:10 UTC, v4voloshyn commented on src/components/Rating/Rating.js
> +  <div className={`${styles.rating} ${styles[`rating_theme_${theme}`]}`}>
Апка наче немає темної теми. Чи може я не бачу десь перемикача?

2023-04-16 15:16 UTC, v4voloshyn commented on src/components/ScrollToTop/ScrollToTop.js
> +export default ScrollToTop;
ScrollToTop це скоріше не компонент а хук.

2023-04-16 15:22 UTC, v4voloshyn commented on src/components/Skills/Skills.js
> +    >
Стилі з константи варто перемістити у .scss файл компоненту

2023-04-16 15:23 UTC, v4voloshyn commented on src/components/Spinner/Spinner.scss
> +	display: flex;
повторення властивості

2023-04-16 15:31 UTC, v4voloshyn commented on src/components/Spinner/Spinner.js
> +  >
Можливо варто винести інлайн стилі в .scss файл компоненту? Тут інлайн стилі перекривають класові тому перші просто можна перенести в styles.overlay

2023-04-16 15:35 UTC, v4voloshyn commented on src/pages/CoursePage/CoursePage.js
> +              <Rating rating={rating} theme="dark" />
Пропс ```theme```, можливо поки що, не актуальний на даному етапі проекту.

2023-04-16 15:38 UTC, v4voloshyn commented on src/pages/CoursePage/CoursePage.js
> +              alt="Course prewiev"
preview*  
Одруківок допомагає уникнути VSCode Extension: Code Spell Checker

2023-04-16 15:39 UTC, v4voloshyn commented on src/pages/CoursePage/CoursePage.scss
> +  width: 100vw;
Дублювання властивості ```width```

2023-04-16 15:47 UTC, v4voloshyn commented on src/pages/ErrorPage/ErrorPage.js
> +      </NavLink>
Тут семантичніше використати просто <Link> адже нам не потрібно знати активний наш лінк чи ні: [React Router <NavLink>](https://reactrouter.com/en/main/components/nav-link)

2023-04-16 15:56 UTC, v4voloshyn requested changes
Рекомендація до всього коду. Там, де використовується JSX розмітка - іменувати файли і компоненти з розширенням ```.jsx```
Вцілому код хороший. Є звісно нюанси, які потрібно виправити, але вони більш стилістичного характеру аніж логічного. Артем - 👍

2023-04-17 14:28 UTC, yulyaolshanska commented on src/pages/CoursePage/CoursePage.scss
> +  width: 100vw;
Дублювання коду width

2023-04-17 14:28 UTC, yulyaolshanska commented on api/client.js
> +  baseURL: 'https://api.wisey.app/api/v1',
You can enter an address in .env or into a constant

2023-04-17 14:28 UTC, yulyaolshanska commented on hooks/usePagination.js
> +const range = (start, end) => {
You may need to choose a more informative name for the variable, to understand what this range is

2023-04-17 14:28 UTC, yulyaolshanska commented on hooks/usePagination.js
> +      );
Add empty line

2023-04-17 14:28 UTC, yulyaolshanska commented on hooks/usePagination.js
> +      const middleRange = range(leftSiblingIndex, rightSiblingIndex);
Add empty line

2023-04-17 14:28 UTC, yulyaolshanska commented on index.scss
> +  background-color: #fafbfd;
You can use theme with colors.
In the future, if your design will be changed, it would be easier to change color.

2023-04-17 14:28 UTC, yulyaolshanska commented on src/components/CourseCard/CourseCard.scss
> +	color: #122b46;
You can use theme with colors.
In the future, if your design will be changed, it would be easier to change color.

2023-04-17 14:28 UTC, yulyaolshanska commented on src/components/CourseCard/CourseCard.scss
> +  max-height: 50px;
Why is there a max-height here if there is already a fixed height?

2023-04-17 14:28 UTC, yulyaolshanska commented on src/components/CourseCard/CourseCard.scss
> +  color: #4d5c6d;
You can use theme with colors.
In the future, if your design will be changed, it would be easier to change color.

2023-04-17 14:28 UTC, yulyaolshanska commented on src/components/Pagination/Pagination.scss
> +  box-sizing: border-box;
It's better to add box-sizing: border-box to index.scss

2023-04-17 14:28 UTC, yulyaolshanska commented on src/components/Pagination/Pagination.scss
> +		&::before {
Hard to read when there are so many levels of nesting

2023-04-17 14:28 UTC, yulyaolshanska commented on src/components/Popup/Popup.scss
> +    font-weight: bold;
It is better to use numeric values for font-weight

2023-04-17 14:28 UTC, yulyaolshanska commented on src/pages/CoursePage/CoursePage.scss
> +  background-color: #29303b;
You can use a theme with colors.
In the future, if your design will be changed, it would be easier to change color.

2023-04-17 14:28 UTC, yulyaolshanska commented on src/pages/CoursePage/CoursePage.scss
> +    box-sizing: border-box;
These styles are already in the file reset.scss  (*,
*::before,
*::after {
  box-sizing: border-box;
})

2023-04-17 14:28 UTC, yulyaolshanska commented on src/pages/ErrorPage/ErrorPage.scss
> +  color: white;
It's better to replace it with color: #fff

2023-04-17 14:36 UTC, yulyaolshanska commented on src/components/Video/Video.js
> +    if (canPlay) setShowPreview((prevState) => !prevState);
Although there is only one line, but for better readability it is better if (canPlay) {
setShowPreview((prevState) => !prevState)
};

2023-04-18 10:41 UTC, artemsukach commented on src/components/Lesson/Lesson.js
> +          </h2>
В мене є ще одне місце, де це не CardVideo, і там не потрібен опис до відео

2023-04-18 10:41 UTC, artemsukach commented on src/components/Rating/Rating.js
> +  <div className={`${styles.rating} ${styles[`rating_theme_${theme}`]}`}>
В мене компонент рейтинга використовується на двох різних сторінках, на різному фоні. Можливо це "костиль, але на той момент я придумав таке рішення.

2023-04-18 10:41 UTC, artemsukach commented on src/components/Skills/Skills.js
> +    >
В даному випадку мені потрібен `viewCount`

2023-04-18 10:41 UTC, artemsukach commented on src/pages/CoursePage/CoursePage.js
> +              alt="Course prewiev"
Дякую

2023-04-18 16:41 UTC, v4voloshyn commented on src/components/Spinner/Spinner.scss
> +	justify-content: center;
Тут і по багатьох файлах стилів трохи відступи поїхали. Запусти Prittier, щоб пофіксив їх. А загалом - все ОК.

2023-04-18 16:42 UTC, v4voloshyn approved these changes
LGTM!

2023-04-19 10:37 UTC, yulyaolshanska approved these changes

2023-04-25 20:28 UTC, merged